### ISSUE TITLE
Multiple class attributes in bootstrap forms on check widgets

### ISSUE THREAD

**Issue by fpoulain** [stephrdev/django-tapeforms#15]
Hi,

Thanks you so long for tapeforms!

I seen a bug via https://validator.w3.org: for check boxes on bootstrap forms, I was getting something like:
```
<input ... class="form-check-input"  ... class="form-control">
```
leading to validation error. At first I tried to merge to two but actually it deface the form: on bootstrap forms we don't have to add `form-control` on `form-check-input`. So I suppose that the second class attribute is simply ignored by browsers.

On my side I didn't need to add others widget_css_class so I simply dropped it:
```python
class FixBootstrapTapeformMixin(BootstrapTapeformMixin):
    """
    Avoid having multiple class attributes in html.
    """

    def get_widget_css_class(self, field_name, field):
        if field.widget.__class__ in [
            forms.RadioSelect,
            forms.CheckboxSelectMultiple,
            forms.CheckboxInput,
        ]:
            return None
        else:
            return self.widget_css_class or None
```
But it seems that actually the template `bootstrap_multipleinput.html` breaks the logic with the hard-defined `class="form-check-input"`. So I guess the insertion of `form-check-input` should be done at python level rather than template level.

How do you think about it?
Best regards.

**Comment by stephrdev** [comment]
You're totally right. The `form-check-input` should be added in Python for the multiple input widgets. Likely somewhere here: https://github.com/stephrdev/django-tapeforms/blob/master/tapeforms/contrib/bootstrap.py#L55-L70 

As I'm quite limited right now when it comes do development time, I'd be more than happy to review and merge a pull request that fixes the issue and in addition am willing to help if any questions left unclear.

Thanks!
