### ISSUE TITLE
Multiple CSS classes for the field container

### ISSUE THREAD

**Issue by jeromelebleu** [stephrdev/django-tapeforms#7]
If several CSS classes are needed for the field container, it is possible to define them as space-separated string in `field_container_css_class`. It will however result in duplicate CSS classes as it is currently applied like this in the template: `class="{{ container_css_class }} {{ container_css_class }}-{{ field_name }} ..."`. For example, if `container_css_class="foo bar"`, it will result in `class="foo bar foo bar-{{ field_name }}"`.

There will be several way to fix this small issue and especially have a more predictable CSS class name for `...-{{ field_name }}` - e.g. split container_css_class and use only the first, use a dedicated context variable... What do you prefer?

**Comment by stephrdev** [comment]
Good catch. This can be an issue indeed. I'm not a fan of splitting and dropping parts of the css class. I thought of replacing the spaces with dashes? This is also changing the intent of the developer/user but most of the time as unique as possible. Any input on this?

**Comment by jeromelebleu** [comment]
I have never used this facility yet honestly, so I don't have any valuable feedback.
